name: 'Setup Environment'
description: 'Set up Bun runtime'
inputs:
  bun-version:
    description: 'Bun version to use'
    required: false
    default: '1.3.4'
runs:
  using: 'composite'
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
