name: 'Setup Environment'
description: 'Check out repository and set up Bun'
inputs:
  bun-version:
    description: 'Bun version to use'
    required: false
    default: '1.3.4'
runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@v6
    
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
